# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "HAVIT NUMPAD"
product_name = "HAVIT NUMPAD"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "haobo"
chip = "rp2040"


[matrix]
matrix_type = "direct_pin"
direct_pin_low_active = true
direct_pins = [
    ["PIN_20", "PIN_19", "PIN_18"],
]

[layout]
rows = 1
cols = 3
layers = 1
keymap = [
    [
        ["A", "B", "C"],
    ],
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true



[storage]
# Storage feature is enabled by default
# enabled = false