# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "HAVIT NUMPAD"
product_name = "HAVIT NUMPAD"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "GRBT"
chip = "nrf52840"
#board = "nice!nano_v2"

[matrix]
# Input and output pins are mandatory
input_pins = ["P0_31", "P0_29", "P0_02", "P1_15", "P1_13", "P1_11"]
output_pins = ["P0_11", "P1_00", "P0_24", "P0_22"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, row2col config here is valid ONLY when you're using cloud compilation
# row2col = true

[layout]
rows = 6
cols = 4
layers = 2
keymap = [
    [
        ["MO(1)", "LShift", "LCtrl", "LAlt"],
        ["NumLock", "KpSlash", "KpAsterisk", "KpMinus"],
        ["Kp7", "Kp8", "Kp9", "KpPlus"],
        ["Kp4", "Kp5", "Kp6", "_"],
        ["Kp1", "Kp2", "Kp3", "KpEnter"],
        ["Kp0", "_", "KpDot", "_"],
    ],
    [
        ["_", "_", "_", "_"], #Bootloader currently does not work
        ["_", "_", "_", "_"],
        ["_", "_", "_", "_"],
        ["_", "_", "_", "_"],
        ["_", "_", "_", "_"],
        ["_", "_", "_", "_"],
    ]
]

[storage]
# Storage feature is enabled by default
# enabled = false
# Set `clear_storage` to true to clear all the stored info when the keyboard boots
# clear_storage = true

[ble]
enabled = true
# vddh has an internal voltage divider
battery_adc_pin = "vddh"

[rmk]
# The number of available BLE profiles
ble_profiles_num = 1