# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "HAVIT NUMPAD"
product_name = "HAVIT NUMPAD"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "GRBT"
chip = "rp2040"


[matrix]
# Input and output pins are mandatory
input_pins = ["PIN_2", "PIN_3", "PIN_4", "PIN_5", "PIN_6", "PIN_7"]
output_pins = ["PIN_13", "PIN_12", "PIN_11", "PIN_10"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, row2col config here is valid ONLY when you're using cloud compilation
# row2col = true

[layout]
rows = 6
cols = 4
layers = 2
keymap = [
    [
        ["Macro0", "Macro1", "Macro2", "Macro3"],
        ["MO(1)", "KpSlash", "KpAsterisk", "KpMinus"],
        ["Kp7", "Kp8", "Kp9", "KpPlus"],
        ["Kp4", "Kp5", "Kp6", "_"],
        ["Kp1", "Kp2", "Kp3", "KpEnter"],
        ["Kp0", "_", "KpDot", "_"],
    ],
    [
        ["NumLock", "_", "_", "_"], #Bootloader currently does not work
        ["_", "_", "_", "_"],
        ["_", "_", "_", "_"],
        ["_", "_", "_", "_"],
        ["_", "_", "_", "_"],
        ["_", "_", "_", "_"],
    ]
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true



[storage]
# Storage feature is enabled by default
# enabled = false
# Set `clear_storage` to true to clear all the stored info when the keyboard boots
# clear_storage = true